-- =============================================================================
-- Firebird Vector Extension (fbvector) - Usage Examples
-- =============================================================================
-- This script contains SQL examples demonstrating how to store vector embeddings,
-- perform exact k-NN queries using different distance metrics, and optimize
-- queries using computed/expression indexes.

-- 1. Create a Table to Store Items and Vector Embeddings
-- We store the vector as a BLOB with SUB_TYPE BINARY.
CREATE TABLE item_embeddings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    embedding BLOB SUB_TYPE BINARY NOT NULL
);

-- 2. Insert Elements
-- We use vector_from_text() to convert human-readable text arrays into packed binary vectors.
INSERT INTO item_embeddings (title, description, embedding) VALUES (
    'Artificial Intelligence Book', 
    'A guide on machine learning and neural networks.', 
    vector_from_text('[0.12, -0.43, 0.88, 0.05]')
);

INSERT INTO item_embeddings (title, description, embedding) VALUES (
    'Cooking Recipes', 
    'Learn how to bake cakes and sourdough bread.', 
    vector_from_text('[-0.89, 0.02, 0.11, -0.45]')
);

INSERT INTO item_embeddings (title, description, embedding) VALUES (
    'Data Science Course', 
    'Comprehensive training program on statistics, C++, and Python.', 
    vector_from_text('[0.09, -0.39, 0.91, 0.12]')
);

-- 3. Perform Exact k-NN Search using L2 (Euclidean) Distance
-- Finds the 2 closest items to the query vector [0.10, -0.40, 0.90, 0.10]
SELECT 
    id, 
    title, 
    vector_l2_distance(embedding, vector_from_text('[0.10, -0.40, 0.90, 0.10]')) AS l2_dist
FROM item_embeddings
ORDER BY l2_dist ASC
OFFSET 0 ROWS FETCH NEXT 2 ROWS ONLY;

-- 4. Perform Cosine Distance Similarity Search
-- Cosine Distance ranges from 0 (identical) to 2 (orthogonal/opposite).
SELECT 
    id, 
    title, 
    vector_cosine_distance(embedding, vector_from_text('[0.10, -0.40, 0.90, 0.10]')) AS cosine_dist
FROM item_embeddings
ORDER BY cosine_dist ASC
OFFSET 0 ROWS FETCH NEXT 2 ROWS ONLY;

-- 5. Perform Inner Product (Dot Product) Search
-- Often used for maximum inner product search (MIPS) on normalized vectors.
SELECT 
    id, 
    title, 
    vector_inner_product(embedding, vector_from_text('[0.10, -0.40, 0.90, 0.10]')) AS dot_product
FROM item_embeddings
ORDER BY dot_product DESC
OFFSET 0 ROWS FETCH NEXT 2 ROWS ONLY;

-- 6. Perform L1 (Manhattan) Distance Search
SELECT 
    id, 
    title, 
    vector_l1_distance(embedding, vector_from_text('[0.10, -0.40, 0.90, 0.10]')) AS l1_dist
FROM item_embeddings
ORDER BY l1_dist ASC;

-- 7. Inspect Vector Dimensions & Magnitude
SELECT 
    title, 
    vector_dims(embedding) AS dimension_count, 
    vector_norm(embedding) AS magnitude
FROM item_embeddings;

-- 8. Create and Use a Computed/Expression Index on Vector Magnitude
-- Firebird allows indexes on expressions. This is useful if we frequently filter 
-- or sort items by their vector length/norm, which avoids computing norms on the fly.
CREATE INDEX idx_item_embedding_norm 
    ON item_embeddings 
    COMPUTED BY (vector_norm(embedding));

-- Query that utilizes the expression index:
-- Finds items whose vector magnitude is close to 1.0 (unit vectors)
SELECT 
    id, 
    title, 
    vector_norm(embedding) AS magnitude
FROM item_embeddings
WHERE vector_norm(embedding) BETWEEN 0.95 AND 1.05;

-- =============================================================================
-- NEW EXAMPLES (v1.0 ADDITIONS)
-- =============================================================================

-- 9. Metadata Filtering / Hybrid Search Query
-- Combines text prefix match or structured categories with vector calculations.
SELECT 
    id, 
    title,
    vector_cosine_distance(embedding, vector_from_text('[0.10, -0.40, 0.90, 0.10]')) AS score
FROM item_embeddings
WHERE title LIKE 'Art%' OR description LIKE '%C++%'
ORDER BY score ASC;

-- 10. Optional Real-Time Sidecar Sync Trigger Setup
-- Automatically notifies the optional background sidecar daemon (fbvector_sidecar) 
-- on inserts, updates, and deletes to keep the in-memory HNSW ANN graph in sync.

-- A. Trigger for Insert and Update operations
CREATE OR ALTER TRIGGER trg_item_embeddings_sync_aiu FOR item_embeddings
ACTIVE AFTER INSERT OR UPDATE POSITION 100
AS
BEGIN
    -- Call the sidecar notifier UDR: action = 1 (Insert/Update)
    SELECT vector_sidecar_sync(new.id, 1, new.embedding) FROM rdb$database;
END;

-- B. Trigger for Delete operations
CREATE OR ALTER TRIGGER trg_item_embeddings_sync_ad FOR item_embeddings
ACTIVE AFTER DELETE POSITION 100
AS
BEGIN
    -- Call the sidecar notifier UDR: action = 2 (Delete)
    SELECT vector_sidecar_sync(old.id, 2, NULL) FROM rdb$database;
END;

